name = "cf-tail"
main = "index.ts"
compatibility_date = "2024-07-29"

[vars]
POSTHOG_API_KEY="https://i.posthog.com"

LOG_PREFIX="event\t"

#See: https://posthog.com/docs/data/persons
POSTHOG_PROCESS_PERSON_PROFILE=false

# Use `wrangler set --env POSTHOG_API_KEY=secret` to set API key
